name: Pages

# 触发器、分支
on:
  push:
    branches:
      - gh-pages  # default branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup Node.js 20.x
        uses: actions/setup-node@master
        with:
          node-version: 20.12.2

      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install
          npm install hexo-deployer-git --save

      - name: Setup Deploy Private Key
        env:
          HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Git Infomation
        run: |
          git --version
          git config --global user.name 'Xsyin' 
          git config --global user.email 'shouyinxu@163.com'
      - name: Deploy Hexo
        run: |
          hexo clean
          hexo generate 
          hexo deploy
      - name: Get the output
        run: |
          echo "${{ steps.deploy.outputs.notify }}"
  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        with:
          # 源仓库
          source-repo: git@github.com:Xsyin/Xsyin.github.io.git
          # 目标仓库
          destination-repo: git@gitee.com:xsyin/blog.git
  reload-pages:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: xsyin
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: xsyin/blog
          branch: master